### ISSUE TITLE
リンクについてtextlint-rule-prhの対象にならない

### ISSUE THREAD

**Issue by tetsuya-ki** [textlint-rule/textlint-rule-prh#105]
## 事象

自分の環境では、`[xxx](yyy)`や`<yyy>`のようなリンクについて、textlint-rule-prhの対象になりません。

checkLinkをtrueとして設定すればリンクも対象になるかと期待したのですが、対象にならないままでした。
こちらは仕様なのでしょうか？　それとも環境(Apple M2)が悪いのでしょうか...。

![image](https://github.com/textlint-rule/textlint-rule-prh/assets/64536338/8a2a8a59-33d9-4a15-9c55-d0e69e37af8d)

たとえば、以下のようなリンクがある場合、textlint対象になって欲しいと思っています。

```md
- [Title](Link) -> NG(NamedLink)
```

このように設定しました。

```yml
  - expected: NamedLink
    pattern:
      - /\[Title\]\(Link\)/
```

## 参考情報

checkEmphasis:true, checkHeader:falseは効いているため、checkLink:trueの設定箇所誤りではなさそうです。
<https://github.com/textlint-rule/textlint-rule-prh/blob/master/README.md#options>

## 環境

npx: 10.2.4
textlint: v14.0.4
Application: Visual Studio Code  - Insiders
Version: 1.89.0-insider (Universal)
Commit: 903ce35c77c7b5714a2d9063b9f1d9bc2956d07c
Date: 2024-04-11T05:50:09.275Z (17 hrs ago)
Electron: 28.2.8
ElectronBuildId: 27744544
Chromium: 120.0.6099.291
Node.js: 18.18.2
V8: 12.0.267.19-electron.0
OS: Darwin arm64 21.6.0

**Comment by azu** [comment]
[`Title`]
checkLinkはリンクのTitle部分だけを対象にしてるのでURL部分はマッチしないですね。
あくまで人間に表示されるのは、Title部分だけなのでprhではレンダリングして人に見える部分だけを対象にしてます。

**Comment by tetsuya-ki** [comment]
リンクのURLをlintできればいいなと思っていたのですが、
対象外ということで承知しました。

お忙しい中、ご回答ありがとうございました。
