### ISSUE TITLE
Proposal: Add options to customize filter AST type

### ISSUE THREAD

**Issue by Leko** [textlint-rule/textlint-rule-prh#33]
Currently, filtered AST types are Link, Image, BlockQuote, Emphasis.
https://github.com/textlint-rule/textlint-rule-prh/blob/dd4bb87109a10ed428eee8baee76925b6396c032/src/textlint-rule-prh.js#L136

I want to add `Header` to the blacklist.
But it cannot set as default behavior. It's not needed in many use cases.
So I propose to support `ignoreSyntax` option.

- Type: `Array<String>` (optional)
- Default values: `[Syntax.Link, Syntax.Image, Syntax.BlockQuote, Syntax.Emphasis]`

How about it?

**Comment by Leko** [comment]
@azu Then, what about `checkHeader` option?

Naming rule: `{prefix}{NodeType}`

- checkLink: `boolean`, default: `false`
- checkImage: `boolean`, default: `false`
- checkBlockQuote: `boolean`, default: `false`
- checkEmphasis: `boolean`, default: `false`
- checkHeader: `boolean`, default: `true`

Other possibilities of prefix:

- lint (ex. lintHeader)
- visit (ex. visitHeader)
- skip (ex. skipHeader)

**Comment by azu** [comment]
I like `visitHeader`, but it is non-intuitive naming.
`checkHeader` is passable.
